Repository GULAG/gulag.github.io, pull requests merged in 2020-10, with the labels that each got.

#1 added cname to root site
  content/extra/CNAME
  favicon.ico
  pelicanconf.py
  publishconf.py
  tasks.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#39 added theme and favicon
  .github/workflows/build.yml
  .github/workflows/publish.yml
  pelican-themes/bootstrap2-dark/LICENSE.txt
  pelican-themes/bootstrap2-dark/README.md
  pelican-themes/bootstrap2-dark/screenshot.png
  pelican-themes/bootstrap2-dark/static/css/bootstrap-responsive.dark.css
  pelican-themes/bootstrap2-dark/static/css/bootstrap.dark.css
  pelican-themes/bootstrap2-dark/static/css/font-awesome.css
  pelican-themes/bootstrap2-dark/static/css/pygments.css
  pelican-themes/bootstrap2-dark/static/font/fontawesome-webfont.eot
  pelican-themes/bootstrap2-dark/static/font/fontawesome-webfont.svg
  pelican-themes/bootstrap2-dark/static/font/fontawesome-webfont.svgz
  pelican-themes/bootstrap2-dark/static/font/fontawesome-webfont.ttf
  pelican-themes/bootstrap2-dark/static/font/fontawesome-webfont.woff
  pelican-themes/bootstrap2-dark/static/img/favicon.ico
  pelican-themes/bootstrap2-dark/static/img/glyphicons-halflings-white.png
  pelican-themes/bootstrap2-dark/static/img/glyphicons-halflings.png
  pelican-themes/bootstrap2-dark/static/js/autosidebar.js
  pelican-themes/bootstrap2-dark/static/js/bootstrap.min.js
  pelican-themes/bootstrap2-dark/static/js/jquery-1.7.2.min.js
  pelican-themes/bootstrap2-dark/templates/analytics.html
  pelican-themes/bootstrap2-dark/templates/archives.html
  pelican-themes/bootstrap2-dark/templates/article.html
  pelican-themes/bootstrap2-dark/templates/article_infos.html
  pelican-themes/bootstrap2-dark/templates/author.html
  pelican-themes/bootstrap2-dark/templates/authors.html
  pelican-themes/bootstrap2-dark/templates/base.html
  pelican-themes/bootstrap2-dark/templates/categories.html
  pelican-themes/bootstrap2-dark/templates/category.html
  pelican-themes/bootstrap2-dark/templates/comments.html
  pelican-themes/bootstrap2-dark/templates/disqus_script.html
  pelican-themes/bootstrap2-dark/templates/github.html
  pelican-themes/bootstrap2-dark/templates/index.html
  pelican-themes/bootstrap2-dark/templates/page.html
  pelican-themes/bootstrap2-dark/templates/pagination.html
  pelican-themes/bootstrap2-dark/templates/piwik.html
  pelican-themes/bootstrap2-dark/templates/search_sidebar.html
  pelican-themes/bootstrap2-dark/templates/sidebar.html
  pelican-themes/bootstrap2-dark/templates/tag.html
  pelican-themes/bootstrap2-dark/templates/taglist.html
  pelican-themes/bootstrap2-dark/templates/tags.html
  pelican-themes/bootstrap2-dark/templates/translations.html
  pelican-themes/bootstrap2-dark/templates/twitter.html
  pelican-themes/bootstrap2-dark/templates/twitter_profile.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#40 #2 | Guia para hacktoberfest
  hacktoberfest.md
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted

#41 Traducción de hacktoberfest.md al portugués
  hacktoberfestptbr.md
Labels: documentation, good first issue, hacktoberfest, hacktoberfest-accepted

#42 eliminadas paginas demo
  content/articles/2020-10-10-aporte-uno.md
  content/articles/2020-10-10-gatito.md
  content/articles/2020-10-10-prueba-de-articulo.md
  content/pages/super-pagina.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#43 #3 | Issue 03 | Actualizar readme
  README.md
  hacktoberfest.md
  hacktoberfestptbr.md
Labels: documentation, enhancement, hacktoberfest, hacktoberfest-accepted

#44 #10 | Issue 10 | Migracion 02 - Completa
  content/articles/2019-10-07-invitacion-reunion-octubre.md
  content/articles/2019-11-03-invitacion-reunion-noviembre.md
  content/articles/2020-04-11-invitacion-reunion-abril.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted
