Repository GULAG/gulag.github.io, pull requests merged in 2022-10, with the labels that each got.

#119 Hacktoberfest | actualizacion de github actions workflows
  .github/workflows/build.yml
  .github/workflows/publish.yml
Labels: enhancement, Hacktoberfest, ready for review

#120 Articulo/2022 10 08 hacktoberfest2022
  content/articles/2022-10-08-HacktoberFest-2022.md
  content/articles/2022-10-08-HacktoberFest-2022/hackt1.png
  content/articles/2022-10-08-HacktoberFest-2022/hackt2.png
Labels: enhancement, Hacktoberfest, ready for review

#121 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: enhancement, Hacktoberfest, ready for review

#122 Se agregó información para los asistentes
  content/articles/2022-10-08-HacktoberFest-2022.md
Labels: ready for review

#124 Hacktoberfest 2022 - Fix issue 30
  content/articles/2016-07-05-Bits-Libres-RuSL.md
  content/articles/2016-08-10-Bits-Libres-Tux-Espacio.md
  content/articles/2016-08-11-avances-congreso-2016.md
  content/articles/2016-09-07-Bits-Libres-Congreso-Software-Libre.md
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted, ready for review

#125 Migracion 12
  content/articles/2018-01-11-invitacion-reunion-enero.md
  content/articles/2018-02-03-Bits-Libres-Mantener-la-confianza.md
  content/articles/2018-02-10-invitacion-reunion-febrero.md
  content/articles/2018-03-03-invitacion-reunion-marzo.md
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted, ready for review

#126 Migracion 13
  content/articles/2017-11-13-Resumen-reunion-noviembre.md
  content/articles/2017-12-03-Bits-Libres-Tiempos-de-compartir.md
  content/articles/2017-12-06-invitacion-reunion-diciembre.md
  content/articles/2018-01-03-Bits-Libres-Adaptarse-al-cambio.md
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted, ready for review

#128 Migracion 06
  content/articles/2019-01-08-invitacion-reunion-enero.md
  content/articles/2019-02-01-Bits-Libres-De-eso-se-trata.md
  content/articles/2019-02-01-invitacion-reunion-febrero.md
  content/articles/2019-03-01-Bits-Libres-Mujer-y-nina-en-la-ciencia.md
Labels: enhancement, Hacktoberfest, ready for review

#131 Hacktoberfest | Fix issue 29, migracion 21
  content/articles/2016-09-23-congreso.md
  content/articles/2016-09-25-resumen-congreso.md
  content/articles/2016-10-05-Bits-Libres-Soberania-Tecnologica.md
  content/articles/2016-10-09-reunion-octubre.md
Labels: documentation, enhancement, Hacktoberfest, hacktoberfest-accepted, ready for review

#132 Guivaloz/mas redes
  pelican-themes/bs5/templates/aside-about.html
  pelican-themes/bs5/templates/navigation.html
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted, ready for review

#139 Reunión de agosto
  content/articles/2022-08-20-reunion-agosto.md
Labels: enhancement, Hacktoberfest, ready for review

#138 Reunión de junio
  content/articles/2022-06-17-reunion-junio.md
Labels: enhancement, Hacktoberfest, ready for review

#137 Reunión de mayo
  content/articles/2022-05-13-reunion-mayo.md
Labels: enhancement, Hacktoberfest, ready for review

#133 Articulo-2019-01-01- UPDATE MIGRACION 7
  content/articles/2019-01-01-Bits-Libres-Trabajemos-con-transparencia.md
  content/articles/2022-09-29-congreso-2022.md~
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted, ready for review

#134 articulo 2018-12-13 update MIGRACION 7
  content/articles/2018-12-13-te-esperamos-en-telegram.md
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted, ready for review

#135 articulo 2018-12-01 Update Migración 7
  content/articles/2018-12-01-Bits-Libres-Compartiendo-lo-mejor-de-nosotros.md
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted, ready for review

#136 Articulo 2018-10.09 update Migración 7
  content/articles/2018-10-08-invitacion-reunion-octubre.md
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted, ready for review

#140 Actualización de Artículos Migración 8
  content/articles/2018-09-01-avances-congreso-2018.md
  content/articles/2018-09-07-congreso-2018.md
  content/articles/2018-09-08-resumen-congreso-2018.md
  content/articles/2018-10-05-Infografia-Espacial-con-Software-Libre.md
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted, ready for review

#123 Hacktoberfest-Update README
  README.md
  README_es_MX.md
Labels: documentation, enhancement, Hacktoberfest, hacktoberfest-accepted

#142 Migración 10 de issues, actualización de archivos a formato pelican
  content/articles/2018-05-03-Bits-Libres-Sistemas-de-votacion.md
  content/articles/2018-05-28-flisol.md
  content/articles/2018-06-02-Bits-Libres-Interesarnos-en-la-politica.md
  content/articles/2018-07-01-Bits-Libres-Vamos-ganando-pero.md
Labels: enhancement, Hacktoberfest, ready for review

#143 Migración 11 actualización de formatos de archivos pelican
  content/articles/2018-03-04-Bits-Libres-datos-personales-por-un-peso.md
  content/articles/2018-04-02-Bits-Libres-Documento-libre.md
  content/articles/2018-04-03-invitacion-reunion-abril.md
  content/articles/2018-04-28-flisol.md
Labels: enhancement, Hacktoberfest, ready for review

#146 Migración 16, se actualizan archivos a formato pelican
  content/articles/2017-06-11-Bits-Libres-Derecho-A-Cifrar.md
  content/articles/2017-07-08-Bits-Libres-Lean-Los-Contratos.md
  content/articles/2017-07-10-PSPP_DefVar.md
  content/articles/2017-08-01-Bits-Libres-Sobre-la-Neutralidad-de-la-Red.md
Labels: enhancement, ready for review

#145 Migración 15, se actualizan los archivos a formato pelican
  content/articles/2017-08-23-avances-congreso-2017.md
  content/articles/2017-09-01-Bits-Libres-Beneficios-de-compartir.md
  content/articles/2017-09-12-resumen-congreso-2017.md
  content/articles/2017-10-01-Bits-Libres-Mas-transparencia-por-favor.md
Labels: documentation, enhancement, Hacktoberfest, hacktoberfest-accepted, ready for review

#144 Migración 14 actualización de formato a pelican
  content/articles/2017-10-09-software-hardware-libres-astronomia-semana-mundial-espacio-2017.md
  content/articles/2017-10-10-invitacion-reunion-octubre.md
  content/articles/2017-11-02-Bits-Libres-Ahora-es-mas-facil.md
  content/articles/2017-11-07-invitacion-reunion-noviembre.md
Labels: documentation, enhancement, Hacktoberfest, hacktoberfest-accepted, ready for review

#148 Migración 20 - Completada
  content/articles/2016-10-16-invitacion-reunion-noviembre.md
  content/articles/2016-11-09-Bits-Libres-Va-Una-Idea.md
  content/articles/2016-11-13-reunion-noviembre.md
  content/articles/2016-12-10-Bits-Libres-Ser-Nuestro-Propio-Hacker.md
Labels: documentation, enhancement, good first issue, Hacktoberfest, ready for review

#141 Migración 9 actualización de archivos
  content/articles/2018-07-07-invitacion-reunion-julio.md
  content/articles/2018-08-01-Bits-Libres-Migracion.md
  content/articles/2018-08-02-ActualizarDebian.md
  content/articles/2018-08-09-invitacion-reunion-agosto.md
Labels: enhancement, Hacktoberfest, ready for review

#154 Issue 152 | Migracion 01
  content/articles/2017-04-27-pspp1.md
Labels: enhancement, good first issue, Hacktoberfest, hacktoberfest-accepted, ready for review

#156 issue 149 migracion02 #Hacktoberfest
  content/articles/2022-10-14-reunion-octubre.md
Labels: enhancement, Hacktoberfest, hacktoberfest-accepted, ready for review

#158 Pspp importar datos
  content/articles/2022-10-28-PSPP-impData.md
  content/articles/2022-10-28-PSPP-impData/01importar.png
  content/articles/2022-10-28-PSPP-impData/02selArchivo.png
  content/articles/2022-10-28-PSPP-impData/03selRango.png
  content/articles/2022-10-28-PSPP-impData/04ajuste.png
  content/articles/2022-10-28-PSPP-impData/Datos.csv
  content/articles/2022-10-28-PSPP-impData/Datos.ods
  content/articles/2022-10-28-PSPP-impData/Datos.xls
  content/articles/2022-10-28-PSPP-impData/PSPP.png
Labels: Hacktoberfest, hacktoberfest-accepted

#161 Migracion Full del Issue 151 Version 2
  content/articles/2014-05-19-revolucionate-a-ti-mismo-se-un-programador.md
Labels: Hacktoberfest, hacktoberfest-accepted

#162 Se realiza cambio en la barra de navegación
  pelican-themes/bs5/templates/navigation.html
Labels: enhancement, ready for review

#163 Primer entrega de practica de analisis descriptivo con PSPP
  content/articles/2022-10-30-PSPP-practica.md
  content/articles/2022-10-30-PSPP-practica/01selec.png
  content/articles/2022-10-30-PSPP-practica/02circEdad.png
  content/articles/2022-10-30-PSPP-practica/03talla.png
Labels: Hacktoberfest, hacktoberfest-accepted

#167 Traducción al inglés del archivo CONTRIBUTING_es_MX
  CONTRIBUTING_en_US.md
Labels: documentation, enhancement, good first issue, Hacktoberfest, hacktoberfest-accepted, ready for review

#168 Basedwaifuu/issue25
  content/articles/2017-05-03-Bits-Libres-Derecho-A-La-Privacidad.md
  content/articles/2017-05-13-flisol.md
  content/articles/2017-05-20-flisol-resumen.md
Labels: documentation, enhancement, good first issue, Hacktoberfest, hacktoberfest-accepted, ready for review
